---
title: "Risk Factors for Non-Routine Discharge in Cerebral Palsy Patients Undergoing Spinal Fusion"
Author: "Katherine Dimitropoulou"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Which patients are at risk for functional decline after fusion surgery?

In medicine, we aim to do no harm. Non-home discharge may be an indicator not only that a patient's quality of life has not improved, but that they suffered functional decline following surgery requiring a higher level of care. In extreme cases, non-home discharge is due to a postoperative death. It can also indicate temporary or permanent loss of function or decline in health status.  

In order to predict which patients do not go home following surgery, we constructed a maximal model including 11 predictors deemed clinically important by two anesthesiologists who care for spinal fusion patients as well as a rehabilitation expert. Using literature and exploratory crosstab analysis we reduced the initial model to 6 predictors: age, history of asthma, chronic lung disease, pre-existing hematologic disorder, need for nutritional support, and severity of scoliosis. 

Age and pre-existing hematologic disorder were identified as significant (alpha = 0.05) predictors of non-routine discharge (any outcome that did not involve the patient returning to their prior home, which includes death in the hospital).

We conclude that for every 1 unit (years) increase in age, the log odds of being discharged home decreased by 0.196 (holding constant other variables in the model). Therefore, for every 1 year increase in age, the odds of home discharge are 0.82x the odds of home discharge for a given patient had they been a year younger. Similarly, if a CP patient has a preoperative diagnosis of hematological disease, the odds of being able to return home after a spinal fusion are 0.28x the odds of returning home if a patient does not have this preoperative diagnosis, holding constant all other variables in the model.

Other factors such as preoperative diagnosis of asthma, chronic lung disease, or need for nutritional supplementation may be predictive of non-home discharge, however larger studies are needed to confirm the magnitude of these effects.